apiVersion: apps/v1
kind: Deployment
metadata:
  name:  react-frontend
  namespace: react-frontend
  labels:
    app:  react-frontend
spec:
  selector:
    matchLabels:
      app: react-frontend
  replicas: 4
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  react-frontend
    spec:
      containers:
      - name:  react-frontend
        image:  kobbyjones/realestate-frontend:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
          