apiVersion: v1
kind: Service
metadata:
  name: react-frontend-service
  namespace: default
spec:
  selector:
    app: react-frontend
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: react-frontend
    protocol: TCP
    port: 80
    targetPort: 80
