apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Release.Name }}-react-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app:  {{ .Release.Name }}-react-frontend
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-react-frontend
  replicas: {{ .Values.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  {{ .Release.Name }}-react-frontend
    spec:
      containers:
      - name:  {{ .Release.Name }}-react-frontend
        image:  {{ .Values.image.repository }}:{{ .Values.image.tag }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{.Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
        ports:
        - containerPort: 80
          