namespace: helm
replicas: 4
image:
  repository: kobbyjones/realestate-frontend
  tag: latest
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 100m
    memory: 100Mi
service:
  type: NodePort
  port: 80
  nodePort: 30080
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800